### ISSUE TITLE
'dh deploy' command fails after multiple component updates

### ISSUE THREAD

**Issue by hatati** [ortelius/compupdate#14]
We use the dh tool in our jenkins pipeline to update and deploy components. After multiple new component and application versions, the 'deploy' command suddenly stops working with the following error message:

```
+ dh deploy --dhurl https://ortelius.obex.schantz.com --dhuser **** --dhpass **** --appname GLOBAL.Keylane.Obex.Obex Platform R39 --appversion 39.0.0 --deployenv GLOBAL.Keylane.Obex.Obex_Platform.dev.azure-nightly-environment --compattr ChartRepo:artifactory --compattr ChartRepoUrl:https://artifactory.schantz.com/artifactory/helm --compattr ChartVersion:1.0.4 --compattr Chart:artifactory/ui --compattr HelmRepoUser: --compattr HelmRepoPass: --compattr DockerUser: --compattr DockerPass: --compattr HelmTemplate:/tmp/ui.yaml --deploydata /tmp/compdata.json
Traceback (most recent call last):
File "/usr/local/bin/dh", line 1204, in <module>
main()
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1137, in __call__
return self.main(*args, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1062, in main
rv = self.invoke(ctx)
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1404, in invoke
return ctx.invoke(self.callback, **ctx.params)
File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 763, in invoke
return __callback(*args, **kwargs)
File "/usr/local/bin/dh", line 447, in main
data = dhapi.log_deploy_application(dhurl, cookies, deploydata)
File "/usr/local/lib/python3.6/dist-packages/deployhub/dhapi.py", line 1648, in log_deploy_application
data['deployid'] = result.get('deployid', -1)
AttributeError: 'NoneType' object has no attribute 'get'
```

The only known solution is to delete the whole component and application chain which isn't a good solution.

**Comment by sbtaylor15** [comment]
What is in the /tmp/compdata.json file when the deployment fails?  Also, we need to check the server side logs for an exception since the result variable does not appear to be a valid object.

**Comment by hatati** [comment]
The error logs have passed the retainment time for the build server. When they arrive again I will past them here

**Comment by hatati** [comment]
The issue hasn't been observed for a long time so closing this
